### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by romildo** [derat/font-config-info#6]
I am not finding any license reference for this project. What is the license?

**Comment by derat** [comment]
I think I didn't choose a license initially because this was just a little one-off diagnostic program that I wrote to help some users diagnose font issues. Are you hoping to distribute the code or use it somewhere?

**Comment by romildo** [comment]
I am hoping to package it for [NixOS](https://nixos.org).

It would also be helpful to have a release for that purpose.

**Comment by derat** [comment]
Thanks, that sounds fine to me! I'm checking with a few past contributors, but I hope to use the BSD 3-clause license and tag a release soon.

**Comment by derat** [comment]
Okay, package away: https://github.com/derat/font-config-info/releases/tag/v1.0.0

**Comment by romildo** [comment]
Thanks.
